## Description of the test case 16
## x tenants following different distributions of page accesses

tenants = [
    {
        'tenant_id': 1,
        'priority_level': 5,
        'database_size': 100000,
        'minimum_buffer_size': 800,
        'base_buffer_size': 2000,
        'maximum_buffer_size': 5000,
        'page_accesses_dist': [
          {
            'type': 'pareto_with_correlated_references',
            'first_correlated_reference_min_distance': 2.0,
            'first_correlated_reference_max_distance': 4.0,
            'correlated_reference_distance_growth_factor': 1.6,
            'max_correlated_references': 15,
            'parameter': 0.05,
            'length': 25000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 4,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 2,
        'priority_level': 5,
        'database_size': 80000,
        'minimum_buffer_size': 800,
        'base_buffer_size': 2000,
        'maximum_buffer_size': 5000,
        'page_accesses_dist': [
          {
            'type': 'pareto_with_correlated_references',
            'first_correlated_reference_min_distance': 1.5,
            'first_correlated_reference_max_distance': 4.0,
            'correlated_reference_distance_growth_factor': 1.7,
            'max_correlated_references': 8,
            'parameter': 0.05,
            'length': 50000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 2,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 3,
        'priority_level': 8,
        'database_size': 200000,
        'minimum_buffer_size': 2000,
        'base_buffer_size': 4000,
        'maximum_buffer_size': 10000,
        'page_accesses_dist': [
          {
            'type': 'zipfian_with_correlated_references',
            'first_correlated_reference_min_distance': 1.5,
            'first_correlated_reference_max_distance': 6.0,
            'correlated_reference_distance_growth_factor': 2.0,
            'max_correlated_references': 14,
            'parameter': 1.01,
            'length': 40000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 5,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 4,
        'priority_level': 5,
        'database_size': 120000,
        'minimum_buffer_size': 800,
        'base_buffer_size': 2000,
        'maximum_buffer_size': 5000,
        'page_accesses_dist': [
          {
            'type': 'normal_with_correlated_references',
            'first_correlated_reference_min_distance': 1.5,
            'first_correlated_reference_max_distance': 6.0,
            'correlated_reference_distance_growth_factor': 2.0,
            'max_correlated_references': 14,
            'variance': 4000,
            'length': 50000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 2,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 5,
        'priority_level': 8,
        'database_size': 190000,
        'minimum_buffer_size': 2000,
        'base_buffer_size': 4000,
        'maximum_buffer_size': 10000,
        'page_accesses_dist': [
          {
            'type': 'normal_with_correlated_references',
            'first_correlated_reference_min_distance': 1.5,
            'first_correlated_reference_max_distance': 3.0,
            'correlated_reference_distance_growth_factor': 1.6,
            'max_correlated_references': 8,
            'variance': 8000,
            'length': 50000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 4,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 6,
        'priority_level': 5,
        'database_size': 10000,
        'minimum_buffer_size': 800,
        'base_buffer_size': 2000,
        'maximum_buffer_size': 5000,
        'page_accesses_dist': [
          {
            'type': 'zipfian_with_correlated_references',
            'first_correlated_reference_min_distance': 1.5,
            'first_correlated_reference_max_distance': 5.0,
            'correlated_reference_distance_growth_factor': 2.0,
            'max_correlated_references': 10,
            'parameter': 1.01,
            'length': 20000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 5,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 7,
        'priority_level': 5,
        'database_size': 100000,
        'minimum_buffer_size': 800,
        'base_buffer_size': 2000,
        'maximum_buffer_size': 5000,
        'page_accesses_dist': [
          {
            'type': 'zipfian_with_correlated_references',
            'first_correlated_reference_min_distance': 1.5,
            'first_correlated_reference_max_distance': 3.0,
            'correlated_reference_distance_growth_factor': 1.3,
            'max_correlated_references': 14,
            'parameter': 1.01,
            'length': 25000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ] * 4,
        'pages_should_be_renumbered': True,
    },
    {
        'tenant_id': 8,
        'priority_level': 5,
        'database_size': 110000,
        'minimum_buffer_size': 800,
        'base_buffer_size': 2000,
        'maximum_buffer_size': 5000,
        'page_accesses_dist': [
          {
            'type': 'pareto_with_correlated_references',
            'first_correlated_reference_min_distance': 2.0,
            'first_correlated_reference_max_distance': 4.0,
            'correlated_reference_distance_growth_factor': 2.0,
            'max_correlated_references': 5,
            'parameter': 0.05,
            'length': 100000,
            'interval_type': 'uniform',
            'interval_max_value': 1,
          },
        ],
        'pages_should_be_renumbered': True,
    },
]

merge_policy = "batch_merge"
min_batch_length = 30
max_batch_length = 200

total_buffer_size = int(sum([tenant['base_buffer_size'] for tenant in tenants]) * 0.8)